In [53]:
import numpy as np  
import pandas as pd     
import os 
from sklearn.model_selection import train_test_split 
from sklearn.linear_model import LogisticRegression 
from sklearn.tree import DecisionTreeClassifier 
from sklearn.ensemble import RandomForestClassifier 
from sklearn.neighbors import KNeighborsClassifier  
from sklearn.compose import ColumnTransformer 
from sklearn.pipeline import Pipeline 
import warnings 
warnings.filterwarnings('ignore')

In [54]:
os.getcwd()

'e:\\mlproject_medicine_review\\notebooks'

In [55]:
train_df= pd.read_csv(os.path.join(os.path.dirname(os.getcwd()),'artifacts','drugsComTrain_raw','drugsComTrain_raw.csv'))
train_df

,uniqueID,drugName,condition,review,rating,date,usefulCount
0,206461,Valsartan,Left Ventricular Dysfunction,"""It has no side effect, I take it in combinati...",9,20-May-12,27
1,95260,Guanfacine,ADHD,"""My son is halfway through his fourth week of ...",8,27-Apr-10,192
2,92703,Lybrel,Birth Control,"""I used to take another oral contraceptive, wh...",5,14-Dec-09,17
3,138000,Ortho Evra,Birth Control,"""This is my first time using any form of birth...",8,3-Nov-15,10
4,35696,Buprenorphine / naloxone,Opiate Dependence,"""Suboxone has completely turned my life around...",9,27-Nov-16,37
...,...,...,...,...,...,...,...
161292,191035,Campral,Alcohol Dependence,"""I wrote my first report in Mid-October of 201...",10,31-May-15,125
161293,127085,Metoclopramide,Nausea/Vomiting,"""I was given this in IV before surgey. I immed...",1,1-Nov-11,34
161294,187382,Orencia,Rheumatoid Arthritis,"""Limited improvement after 4 months, developed...",2,15-Mar-14,35
161295,47128,Thyroid desiccated,Underactive Thyroid,"""I&#039;ve been on thyroid medication 49 years...",10,19-Sep-15,79
161296,215220,Lubiprostone,"Constipation, Chronic","""I&#039;ve had chronic constipation all my adu...",9,13-Dec-14,116

In [56]:
test_df= pd.read_csv(os.path.join(os.path.dirname(os.getcwd()),'artifacts','drugsComTest_raw','drugsComTest_raw.csv'))
test_df

,uniqueID,drugName,condition,review,rating,date,usefulCount
0,163740,Mirtazapine,Depression,"""I&#039;ve tried a few antidepressants over th...",10,28-Feb-12,22
1,206473,Mesalamine,"Crohn's Disease, Maintenance","""My son has Crohn&#039;s disease and has done ...",8,17-May-09,17
2,159672,Bactrim,Urinary Tract Infection,"""Quick reduction of symptoms""",9,29-Sep-17,3
3,39293,Contrave,Weight Loss,"""Contrave combines drugs that were used for al...",9,5-Mar-17,35
4,97768,Cyclafem 1 / 35,Birth Control,"""I have been on this birth control for one cyc...",9,22-Oct-15,4
...,...,...,...,...,...,...,...
53761,159999,Tamoxifen,"Breast Cancer, Prevention","""I have taken Tamoxifen for 5 years. Side effe...",10,13-Sep-14,43
53762,140714,Escitalopram,Anxiety,"""I&#039;ve been taking Lexapro (escitaploprgra...",9,8-Oct-16,11
53763,130945,Levonorgestrel,Birth Control,"""I&#039;m married, 34 years old and I have no ...",8,15-Nov-10,7
53764,47656,Tapentadol,Pain,"""I was prescribed Nucynta for severe neck/shou...",1,28-Nov-11,20
53765,113712,Arthrotec,Sciatica,"""It works!!!""",9,13-Sep-09,46

In [57]:
df= pd.concat([train_df,test_df])
df

,uniqueID,drugName,condition,review,rating,date,usefulCount
0,206461,Valsartan,Left Ventricular Dysfunction,"""It has no side effect, I take it in combinati...",9,20-May-12,27
1,95260,Guanfacine,ADHD,"""My son is halfway through his fourth week of ...",8,27-Apr-10,192
2,92703,Lybrel,Birth Control,"""I used to take another oral contraceptive, wh...",5,14-Dec-09,17
3,138000,Ortho Evra,Birth Control,"""This is my first time using any form of birth...",8,3-Nov-15,10
4,35696,Buprenorphine / naloxone,Opiate Dependence,"""Suboxone has completely turned my life around...",9,27-Nov-16,37
...,...,...,...,...,...,...,...
53761,159999,Tamoxifen,"Breast Cancer, Prevention","""I have taken Tamoxifen for 5 years. Side effe...",10,13-Sep-14,43
53762,140714,Escitalopram,Anxiety,"""I&#039;ve been taking Lexapro (escitaploprgra...",9,8-Oct-16,11
53763,130945,Levonorgestrel,Birth Control,"""I&#039;m married, 34 years old and I have no ...",8,15-Nov-10,7
53764,47656,Tapentadol,Pain,"""I was prescribed Nucynta for severe neck/shou...",1,28-Nov-11,20
53765,113712,Arthrotec,Sciatica,"""It works!!!""",9,13-Sep-09,46

In [58]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 215063 entries, 0 to 53765
Data columns (total 7 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   uniqueID     215063 non-null  int64
 1   drugName     215063 non-null  object
 2   condition    213869 non-null  object
 3   review       215063 non-null  object
 4   rating       215063 non-null  int64
 5   date         215063 non-null  object
 6   usefulCount  215063 non-null  int64
dtypes: int64(3), object(4)
memory usage: 13.1+ MB

In [59]:
df.isnull().sum()

uniqueID          0
drugName          0
condition      1194
review            0
rating            0
date              0
usefulCount       0
dtype: int64

In [61]:
df['date']=pd.to_datetime(df['date'])
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 215063 entries, 0 to 53765
Data columns (total 7 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   uniqueID     215063 non-null  int64
 1   drugName     215063 non-null  object
 2   condition    213869 non-null  object
 3   review       215063 non-null  object
 4   rating       215063 non-null  int64
 5   date         215063 non-null  datetime64[ns]
 6   usefulCount  215063 non-null  int64
dtypes: datetime64[ns](1), int64(3), object(3)
memory usage: 13.1+ MB

In [ ]:
df.dropna(inplace=True) # remove missing value from the whole data set 
df.shape

(213869, 7)

In [63]:
#  feature engg.  
df['total_review'] =df['drugName'] + df['condition'] +df['review']
df.head()

,uniqueID,drugName,condition,review,rating,date,usefulCount,total_review
0,206461,Valsartan,Left Ventricular Dysfunction,"""It has no side effect, I take it in combinati...",9,2012-05-20,27,"ValsartanLeft Ventricular Dysfunction""It has n..."
1,95260,Guanfacine,ADHD,"""My son is halfway through his fourth week of ...",8,2010-04-27,192,"GuanfacineADHD""My son is halfway through his f..."
2,92703,Lybrel,Birth Control,"""I used to take another oral contraceptive, wh...",5,2009-12-14,17,"LybrelBirth Control""I used to take another ora..."
3,138000,Ortho Evra,Birth Control,"""This is my first time using any form of birth...",8,2015-11-03,10,"Ortho EvraBirth Control""This is my first time ..."
4,35696,Buprenorphine / naloxone,Opiate Dependence,"""Suboxone has completely turned my life around...",9,2016-11-27,37,"Buprenorphine / naloxoneOpiate Dependence""Subo..."

In [64]:
df['clean_review'] = (df['total_review']
                      .str.lower()
                      .str.replace(r'\d','',regex=True)
                      .str.replace(r'[^\w\s]','',regex=True)
                      )
df['clean_review']

0        valsartanleft ventricular dysfunctionit has no...
1        guanfacineadhdmy son is halfway through his fo...
2        lybrelbirth controli used to take another oral...
3        ortho evrabirth controlthis is my first time u...
4        buprenorphine  naloxoneopiate dependencesuboxo...
                               ...
53761    tamoxifenbreast cancer preventioni have taken ...
53762    escitalopramanxietyive been taking lexapro esc...
53763    levonorgestrelbirth controlim married  years o...
53764    tapentadolpaini was prescribed nucynta for sev...
53765                            arthrotecsciaticait works
Name: clean_review, Length: 213869, dtype: object

In [65]:
from nltk.corpus import stopwords
stop_word=set(stopwords.words('english'))
df['clean_review'] = df['clean_review'].apply(lambda x:' '.join(w for w in x.split() if w not in stop_word)) 
df['clean_review']

0        valsartanleft ventricular dysfunctionit side e...
1        guanfacineadhdmy son halfway fourth week intun...
2        lybrelbirth controli used take another oral co...
3        ortho evrabirth controlthis first time using f...
4        buprenorphine naloxoneopiate dependencesuboxon...
                               ...
53761    tamoxifenbreast cancer preventioni taken tamox...
53762    escitalopramanxietyive taking lexapro escitapl...
53763    levonorgestrelbirth controlim married years ol...
53764    tapentadolpaini prescribed nucynta severe neck...
53765                            arthrotecsciaticait works
Name: clean_review, Length: 213869, dtype: object

In [66]:
# add sentiment column..
df['sentiment'] = df['rating'].apply(lambda x: 'postive' if x>5 else 'negative')
df['sentiment']

0         postive
1         postive
2        negative
3         postive
4         postive
           ...
53761     postive
53762     postive
53763     postive
53764    negative
53765     postive
Name: sentiment, Length: 213869, dtype: object

In [67]:
df_clean= df[['total_review','drugName','condition','sentiment','rating']]
df_clean

,total_review,drugName,condition,sentiment,rating
0,"ValsartanLeft Ventricular Dysfunction""It has n...",Valsartan,Left Ventricular Dysfunction,postive,9
1,"GuanfacineADHD""My son is halfway through his f...",Guanfacine,ADHD,postive,8
2,"LybrelBirth Control""I used to take another ora...",Lybrel,Birth Control,negative,5
3,"Ortho EvraBirth Control""This is my first time ...",Ortho Evra,Birth Control,postive,8
4,"Buprenorphine / naloxoneOpiate Dependence""Subo...",Buprenorphine / naloxone,Opiate Dependence,postive,9
...,...,...,...,...,...
53761,"TamoxifenBreast Cancer, Prevention""I have take...",Tamoxifen,"Breast Cancer, Prevention",postive,10
53762,"EscitalopramAnxiety""I&#039;ve been taking Lexa...",Escitalopram,Anxiety,postive,9
53763,"LevonorgestrelBirth Control""I&#039;m married, ...",Levonorgestrel,Birth Control,postive,8
53764,"TapentadolPain""I was prescribed Nucynta for se...",Tapentadol,Pain,negative,1
53765,"ArthrotecSciatica""It works!!!""",Arthrotec,Sciatica,postive,9

In [69]:
x_review=df_clean['total_review']
y=df_clean['sentiment']
# x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2,random_state=42)

In [70]:
from sklearn.feature_extraction.text import TfidfVectorizer 
tf = TfidfVectorizer(max_features=10000) 
x_review_vector = tf.fit_transform(x_review)
x_review_vector

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 12713120 stored elements and shape (213869, 10000)>

In [71]:
y=y.map({'postive':1,'negative':0})
y

0        1
1        1
2        0
3        1
4        1
        ..
53761    1
53762    1
53763    1
53764    0
53765    1
Name: sentiment, Length: 213869, dtype: int64

In [72]:
# classfication steps 
x=df_clean[['drugName','condition']]
x

                       drugName                     condition
0                     Valsartan  Left Ventricular Dysfunction
1                    Guanfacine                          ADHD
2                        Lybrel                 Birth Control
3                    Ortho Evra                 Birth Control
4      Buprenorphine / naloxone             Opiate Dependence
...                         ...                           ...
53761                 Tamoxifen     Breast Cancer, Prevention
53762              Escitalopram                       Anxiety
53763            Levonorgestrel                 Birth Control
53764                Tapentadol                          Pain
53765                 Arthrotec                      Sciatica

[213869 rows x 2 columns]

In [76]:
cat_col = x.columns
cat_col

Index(['drugName', 'condition'], dtype='object')

In [77]:
from sklearn.preprocessing import OneHotEncoder,OrdinalEncoder
preporcess = ColumnTransformer(
    transformers=[
   ( 'drug',OrdinalEncoder(),['drugName']),
   ('condition',OneHotEncoder(),['condition'])]
)
preporcess

ColumnTransformer(transformers=[('drug', OrdinalEncoder(), ['drugName']),
                                ('condition', OneHotEncoder(), ['condition'])])